# Generated by Django 4.2.21 on 2026-03-30 21:18

from django.db import migrations, models
import django.db.models.deletion
import triage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_id",
                    models.CharField(
                        default=triage.models.generate_case_id,
                        editable=False,
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "predicted_case_type",
                    models.CharField(
                        choices=[
                            ("FRAUD", "Fraud"),
                            ("LOCKOUT", "Account Lockout"),
                            ("DISPUTE", "Transaction Dispute"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_outcome", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CaseInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_text", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_user", models.BooleanField(default=False)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="triage.supportcase",
                    ),
                ),
            ],
        ),
    ]
